### ISSUE TITLE
Issues in getting started guide

### ISSUE THREAD

**Issue by lategoodbye** [V2GClarity/RISE-V2G#1]
The portable command to build RISE V2G with maven should be `mvn package`, not `maven package` like in the wiki entry under https://wiki.eclipse.org/RISE_V2G.

Btw: Since the repo https://github.com/eclipse/risev2g.git is obsolete, the clone instruction should be updated to the new github repository.

**Comment by MarcMueltin** [comment]
As long as this getting started guide is used by both repositories, I cannot update the github repo information. I added a note in the README file in this repository.

**Comment by MarcMueltin** [comment]
I am currently working on a video-based documentation for RISE V2G. Should be available by end of October. As soon as it's available, I will change the link to the documentation, including a getting started guide for Maven.

**Comment by MarcMueltin** [comment]
The updated documentation is now available as a video-based online course: https://courses.v2g-clarity.com/p/risev2g-basics
