### ISSUE TITLE
Optionally disable XML signatures

### ISSUE THREAD

**Issue by Sevenstax** [V2GClarity/RISE-V2G#11]
Hi, you did some great work with this project!

We have a V2G stack and want to use this server to test our implementation. I got it working but I had to disable the use of XML signatures because our stack in it's current version is missing the XML signature parsing support.

Is there a possibility that the use of XML signatures could be optionally disabled in the config file of the server?

**Comment by MarcMueltin** [comment]
Hi there, 

glad you are working with RISE V2G. :)
Well, if you do not want to use XML signatures, you can set the property "TLSSecurity" in the EVCCConfig.properties to "false". This way you will have a communication via TCP, not secured via TLS. In pure TCP communication, there are no XML signatures applied.

However, if you do use TLS, then XML signatures are mandatory. There is no property to switch to disable XML signatures (as it is not standard conform).

Does that help you?

**Comment by Sevenstax** [comment]
Thank you for the information.

If it's violating the standard then it doesn't make sense to optionally disable it.

**Comment by MarcMueltin** [comment]
One side note: 
To be completely correct: You could use TLS with EIM (External Identification Means). Here, you don't use certificates or digital XML-based signatures. So you can use TLS without using XML signatures. For this, the SECCConfig.properties file needs to set the property "SupportedPaymentOptions" to "ExternalPayment" only.

However, if you use Plug & Charge (property "SupportedPaymentOptions" is set to "Contract" as well), then XML signatures and X.509 certificates are mandatory.

**Comment by Sevenstax** [comment]
I think this is exactly what we need, until we finish our implemenatation of the XML signatures.
