### ISSUE TITLE
Make EXI codec selectable via properties file

### ISSUE THREAD

**Issue by lategoodbye** [V2GClarity/RISE-V2G#12]
The EXI codec has a big impact on the startup time of RiseV2G on embedded devices (OpenEXIcodec is faster than EXIficient). So it would be nice to have a property to select between them.

**Comment by MarcMueltin** [comment]
You can already choose which EXI codec you want to use by commenting the respective line in the constructor of the MessageHandler().

`		setExiCodec(EXIficientCodec.getInstance());
//		setExiCodec(OpenEXICodec.getInstance());`

But having this option instead in the properties file is also a good solution. I will probably add another property.

Could you please tell me the difference in the startup time for each of them, together with the hardware specs?

**Comment by MarcMueltin** [comment]
The big difference in the startup time between OpenEXI and EXIficient in RISE V2G is that OpenEXI uses an already serialized MsgDef XSD schema file, while EXIficient doesn't.
See also https://github.com/V2GClarity/RISE-V2G/blob/master/RISE-V2G-Shared/src/main/java/org/v2gclarity/risev2g/shared/exiCodec/OpenEXICodec.java#L118

I just spoke with the author of EXIficient. There is a faster way to initialize EXIficient. Will provide more insights as soon as I have the information.

Thanks for the catch!

**Comment by MarcMueltin** [comment]
The issue has been resolved by the [latest commit](https://github.com/V2GClarity/RISE-V2G/commit/7cd067c11895cc95b1c388a49d83588e37955de3).
Will let you know as soon as I got more info about the speedup of EXIficient.
