### ISSUE TITLE
Handling in WaitForChargeParameterDiscoveryReq takes too long

### ISSUE THREAD

**Issue by lategoodbye** [V2GClarity/RISE-V2G#13]
Currently the handling in WaitForChargeParameterDiscoveryReq on SECC side takes too long on embedded devices and violate the timing constraint of 2 seconds.

I identified 2 reasons for this:
- an unconditional sleep of 1 second in processIncomingMessage()
- the private key of Mobility Operator Sub-CA 2 is unencrypted from the keystore also within processIncomingMessage()

The following changes fixed it for me (possibly not the right solution):
- reduce the unconditional sleep to 500 ms
- unencrypt and cache the private key within the DummyBackendInterface constructor

**Comment by MarcMueltin** [comment]
This issue has been resolved in commit d8c9fc7. I deleted the unconditional sleep of 1s in processIncomingMessage() of WaitForCertificateInstallationReq.java.
And I shifted the process of reading the private key from the keystore to the constructor as suggested.
