### ISSUE TITLE
Different EXI streams for message fragments

### ISSUE THREAD

**Issue by mrozigor** [V2GClarity/RISE-V2G#16]
Hello.

I don't know if this is a problem or maybe I don't understand EXI encoding, but when I try to verify signature for SalesTariffs it fails on two different codecs (e.g. SECC -> Exificient, EVCC -> Open EXI). It also fails when I try to connect RiseV2G_EVCC implementation with own implementation based on OpenV2G. It is also interesting that signature verification works between different codecs, when whole message is signed (e.g. AuthorizationReq). Do you know something about this issue? Thanks for help and for your efforts into 15118 ;)

**Comment by lategoodbye** [comment]
@mrozigor Could you please provide an example in order to reproduce this issue? Which version of OpenV2G do you use?

**Comment by mrozigor** [comment]
I used OV2G version 0.9.3 as well as latest dev version (r106). Could you confirm that SalesTariffs signature verification between RiseV2G EVCC and SECC (with different codecs on each endpoint) fails?

**Comment by mrozigor** [comment]
It looks like those all EXI codecs encode full messages properly, but fails to encode fragments (gives different outputs).

**Comment by MarcMueltin** [comment]
I can confirm (after testing right now) that only SalesTariff signature verification fails in case you use EXIficient on one side (either EVCC or SECC) and OpenEXI on the other side (either EVCC or SECC). It works properly with CertificateInstallation/CertificateUpate where you also have partial digest creation (of parameters of the message, not just the complete message).

If you use EXIficient on both sides or OpenEXI on both sides, SalesTariff signature verification is successful.

I will have to look into it and will get back to you.

**Comment by mrozigor** [comment]
Thank you very much! After fix (if there will be any) I'll check this with OpenV2G.

**Comment by MarcMueltin** [comment]
Has now been fixed with commit 374e06e

**Comment by mrozigor** [comment]
It works now. Thank you for help!
