### ISSUE TITLE
Charging Loop Counter not always considered

### ISSUE THREAD

**Issue by P3-JanBoldt** [V2GClarity/RISE-V2G#18]
Hello,

Thanks for providing this great tool, it has been very helpful in getting a feel for the V2G communication.

As i have been "playing around" with RiseV2G, i noticed the  `isChargingLoopActive` method and the `chargingLoopCounter` in the DummyEVController, which are used to control the number of charging loops and thus the amount of messages exchanged in between the EVSE and the EV. 

When setting the energy transfer mode to DC_COMBO_CORE (via the EVCCConfig.properties or the `getRequestedEnergyTransferMode` method of the DummyEVController) the amount of exchanged messages increases significantly compared to other transfer modes. Often there are more than 100 CurrentDemandReq/Res and MeteringReceiptReq/Res pairs. Apparently the MeteringRecipt handling does inhibit the correct consideration of the charge loops.

The communication finally terminates when a Signature Exception is thrown at the EVSE side, which seems to be a different issue. 

Could you please confirm this behaviour? - Thank you!

**Comment by MarcMueltin** [comment]
Hi Jan, 

I fixed the issue with commit 0e4b838.
The problem was that the class WaitForMeteringReceiptRes did not check if the chargingLoop is still active. 
Thanks for the hint!
