### ISSUE TITLE
generateCertificates.sh uses a absolute path to openssl

### ISSUE THREAD

**Issue by lategoodbye** [V2GClarity/RISE-V2G#2]
The usage of an absolute path ( /usr/local/Cellar/openssl/1.0.2h_1/bin/ ) to openssl in generateCertificates.sh isn't very portable. It would be better to call openssl directly and let PATH do its job.

**Comment by MarcMueltin** [comment]
Yes, I realized this yesterday as well. I added a hint in the comment section of generateCertificates.sh to be aware of using the right openssl version even after installing a newer openssl with Homebrew. An absolute path might be needed, but should not be part of the RISE V2G project as this is an issue dependent on the user's machine.

Issue is resolved with commit 2267ad7.
