### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by csbac** [V2GClarity/RISE-V2G#22]
Hi!
Am I simply missing the build instructions, or are there none? After a lot of random tries and "find" I finally found out how to build it - maybe someone should write that down for new users?

Just put a simple line "call 'mvn package' in 'RISE-V2G-PARENT' into the README.md?

**Comment by MarcMueltin** [comment]
There is a completely free guide given as a video course, linked on the main page, see "More Information":
"View the [RISE V2G Basics](https://courses.v2g-clarity.com/p/risev2g-basics) online course to get RISE V2G up and running on your computer in under an hour."

In the last of the four videos, there are build instructions.
