### ISSUE TITLE
EXI decoding instruction missing

### ISSUE THREAD

**Issue by basilfx** [V2GClarity/RISE-V2G#25]
I'm playing with the [EXI examples](https://github.com/V2GClarity/RISE-V2G/blob/master/RISE-V2G-Certificates/signature-creation-testdata/README.md), using [Exificient-Gui](https://github.com/EXIficient/exificient-gui), but no matter what I try, I cannot convert it to XML. Either the resulting file is empty, or it throws an exception.

Can you provide the instructions on how to decode an EXI message, if possible for EXIficient-Gui?

I have been using the schema's, and I have converted the hex-encoded example to a binary using `cat input.hex | xxd -r -p  > output.bin`. Then I selected 'EXI to XML' in the program, and played with the settings to match [this source file](https://github.com/V2GClarity/RISE-V2G/blob/master/RISE-V2G-Shared/src/main/java/com/v2gclarity/risev2g/shared/exiCodec/EXIficientCodec.java). I am doing this to understand how EXI works in the context of 15118, and get a feeling for how it works.

**Comment by MarcMueltin** [comment]
Hello there, 
a shorts heads-up: I am currently on vacation but I'll look into it at the latest once I am back at work. Will be beginning of September.

**Comment by basilfx** [comment]
@MarcMueltin, any update on this? Thanks!

**Comment by MarcMueltin** [comment]
I tried to decode some EXI examples using Exificient-GUI myself, but I also was not successful in decoding that EXI into XML documents. I'm afraid I can't help you much right now. I never used Exificient-GUI myself. You would have to contact the creator of Exificient-GUI and see if he or she can help you out.

I'll keep this issue open until we find a solution. This week and the coming week I probably won't find time as I am on business travels, but the week after I have a bit more time.

**Comment by Torrentus** [comment]
Hi Marc, 

I think I read or heard you say once which library you used to generate these examples, but I cannot recall. Can you help me out? We will try and get in touch with the Exificient library maintainers to find out about the cause of this.

Thanks!

Regards,
Remco
