### ISSUE TITLE
Lack of information on the Controller side

### ISSUE THREAD

**Issue by mrbig** [V2GClarity/RISE-V2G#31]
Hello,

During my work with RISE-V2G I've found a few situations where the Controller could use some more detail about the current progress than what is available now.

On the SECC side:
 - details of the CurrentDemandReq like the remainding time or the EVRESSSOC could be useful for the customer
 - current state (and change in the state) would be useful for various charge related processes: when to activate on isolation checking, when to turn on different PSU, etc.

I believe such situations would exist on the EVCC side as well.

I see two approaches here:

A) we could add more methods to IDCEVSEController and the respective interfaces. But there could be always cases that weren't thought of, and also this approach could make the interface cluttered

B) since V2GCommunicationSession is already Observable the controller could use this to subscribe events that expose a higher detail than available now. What I'm thinking of is that a notifyObserver would be called with the current state and the latest received and parsed message every time a message arrives.

I've opened this issue to discuss these possibilities. When there is a decision I'd be glad to send pull requests with the changes.

**Comment by MarcMueltin** [comment]
I'm happy to look at a proposal sent via a pull request and then engage a discussion based on this.

**Comment by MarcMueltin** [comment]
Closed due to inactivity.
