### ISSUE TITLE
Isolationlevel should not be set by the session

### ISSUE THREAD

**Issue by mrbig** [V2GClarity/RISE-V2G#32]
Hello,

At WaitForCableCheckReq:68  (see: https://github.com/V2GClarity/RISE-V2G/blob/master/RISE-V2G-SECC/src/main/java/com/v2gclarity/risev2g/secc/states/WaitForCableCheckReq.java#L64 ) I believe calling the setIsolationlevel is not correct.

As far as I understand isolation checking should be a subsystem that continuously monitors the isolation state from the CableCheck until the end of the charge process.

I believe calling something like activateIsolationMonitoring() / deactivateIsolationMonitoring() would be more correct. Using this the DummyDCEVSEController count change the isolation level to whatever suits most the simulation.

This would also solve the TODO there: the session should read the current isolation level, and reply a EVSEProcessing = ONGOING as long as it is not VALID.

Also this issie could be solved by notifying the controller about state changes like I proposed in issue #31

**Comment by MarcMueltin** [comment]
It would be helpful if you could provide a code fragment which we can discuss.

**Comment by MarcMueltin** [comment]
Closed due to inactivity.
