### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by FabioTerrile** [V2GClarity/RISE-V2G#38]
Hi, your latest modification are missing a correct RISE-V2G-Shared version number update in PARENT, EVCC and SECC: actual Shared version is 1.2.5, but in the latter still reference 1.2.4, so it does not compile.

As a suggestion maybe you can modify Shared reference version number with:

<project.version>${project.version}</project.version>

Regards.

**Comment by MarcMueltin** [comment]
Hi @FabioTerrile, thanks for the hint. I updated the latest release. Could you please try again and let me know whether you still have build problems or the issue is now resolved?

**Comment by FabioTerrile** [comment]
Resolved!
Thank you!
