### ISSUE TITLE
'risev2g' Build Failure, while running 'mvn package' command in Raspberrypi Terminal 

### ISSUE THREAD

**Issue by Babloo-KMR** [V2GClarity/RISE-V2G#39]
Hi, 
The following error has occurred while running 'mvn package' command:

"Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (make-my-jar-with-dependencies) on project evcc: Failed to create assembly: Failed to resolve dependencies for project: org.eclipse.risev2g:evcc:jar:1.0.0-SNAPSHOT: Missing:"

Could someone help me regarding this?

Thanks in advace

**Comment by MarcMueltin** [comment]
It looks as if you were using an old release (1.0.0-SNAPSHOT). Can you please download the newest release 1.2.5 and let me know if you still run into problems? I just ran 'mvn package' on my computer with version 1.2.5 and everything works fine.

**Comment by MarcMueltin** [comment]
Issue seems to be resolved.

**Comment by Babloo-KMR** [comment]
Hi MarcMueltin, the issue got resolved after upgrading to JDK 8. Thanks for the support.
