### ISSUE TITLE
Wrong Filename in generateCertificates.bat

### ISSUE THREAD

**Issue by Hermelinmaster** [V2GClarity/RISE-V2G#44]
Hello Dr. Mültin,

Thank you for all your hard work.
I found a little misstype in your Batch-File for generating the Keys and Certs.
The affectet File is located in 
.\RISE-V2G\RISE-V2G-Certificates\generateCertificates.bat
Line 85 reads as follows:
openssl ecparam -genkey -name prime256v1 | openssl ec -aes-128-cbc -passout file:passphrase.txt -out privateKeys/v2gRootA.key 

But the rest of the script expects a file in 
privateKeys/v2gRootCA.key 

It is just missing a "C".

So thanks again for supporting this marvelous project.

Take care,

Hermelinmaster

**Comment by MarcMueltin** [comment]
Hello @Hermelinmaster, 
sorry for the delay in my response and thank you so much for spotting that typo. I corrected it with the newest commit bc1bdfd41618ec4e62c6653d0418af29d8d45ed0.
