### ISSUE TITLE
ChargingForFree property doesn't have any effect

### ISSUE THREAD

**Issue by lategoodbye** [V2GClarity/RISE-V2G#5]
The property ChargingForFree in the file SECCConfig.properties doesn't have any effect. If i set this property to true there is no effect to the ServiceDiscoveryResponse from the SECC.

**Comment by MarcMueltin** [comment]
Good catch. I will correct it with the next release.

**Comment by MarcMueltin** [comment]
Issue resolved with commit f301e82.
