### ISSUE TITLE
What is the platform to run this demo?

### ISSUE THREAD

**Issue by Shane-pe** [V2GClarity/RISE-V2G#56]
Hi Authors,

Thank you for your contribution on ISO 15118.
I have one simple question, what is the platform you run this demo? e.g. AM335x.
And what's more, run on which kind of OS?
Thanks in advance.

**Comment by MarcMueltin** [comment]
Hi @Shane-pe, the RISE V2G code is platform-independent as Java can run on any OS. It has not been tested in a specific embedded environment.
