### ISSUE TITLE
No IPv6 link-local address found

### ISSUE THREAD

**Issue by BenediktWoermann** [V2GClarity/RISE-V2G#61]
Hello Everyone,

 I get the error 

> FATAL [main] MiscUtils: No IPv6 link-local address found on the network interface 'Software Loopback Interface 1' configured in the properties file

As I am on a windows machine, I have entered the command "route print", but none of the numbers in the interface list work for me. No matter which number (1, 5, 7, 13, 17, 19, 21) I choose, everytime the error above appeares. The interface list looks as followed:

> ===========================================================================
Schnittstellenliste
  7...e8 d8 d1 aa 3c bb ......Intel(R) Ethernet Connection (6) I219-LM
 17...4c 1d 96 1c 41 1c ......Microsoft Wi-Fi Direct Virtual Adapter
 13...4e 1d 96 1c 41 1b ......Microsoft Wi-Fi Direct Virtual Adapter #2
 21...4c e1 73 47 9e 43 ......Realtek USB GbE Family Controller
 19...4c 1d 96 1c 41 1b ......Intel(R) Wi-Fi 6 AX200 160MHz
  5...4c 1d 96 1c 41 1f ........Bluetooth Device (Personal Area Network)
  1...............................................Software Loopback Interface 1
===========================================================================

Does anybody have an idea how I can solve this issue? Thank you very much in advance!

Greetings, Benedikt

**Comment by BenediktWoermann** [comment]
On my Mac it is running fine, but I have to get it to run on windows. So I think, the configuration of the project itself is correct, but for windows, some options of the network adapter have to be changed.

**Comment by BenediktWoermann** [comment]
Solved it! See: https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/configure-ipv6-in-windows  This value was set to 0xFF and I had to change it to 0x00

**Comment by hughsheehy** [comment]
Same issue....following the windows instructions doesn't fix it.
